<?php
/**
 * @file
 * ads_menu.features.inc
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function ads_menu_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "strongarm" && $api == "strongarm") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_image_default_styles().
 */
function ads_menu_image_default_styles() {
  $styles = array();

  // Exported image style: ads_menu_category_thumbnail.
  $styles['ads_menu_category_thumbnail'] = array(
    'name' => 'ads_menu_category_thumbnail',
    'label' => 'ads_menu_category_thumbnail',
    'effects' => array(
      1 => array(
        'label' => 'Scale and crop',
        'help' => 'Scale and crop will maintain the aspect-ratio of the original image, then crop the larger dimension. This is most useful for creating perfectly square thumbnails without stretching the image.',
        'effect callback' => 'image_scale_and_crop_effect',
        'dimensions callback' => 'image_resize_dimensions',
        'form callback' => 'image_resize_form',
        'summary theme' => 'image_resize_summary',
        'module' => 'image',
        'name' => 'image_scale_and_crop',
        'data' => array(
          'width' => 32,
          'height' => 32,
        ),
        'weight' => 1,
      ),
    ),
  );

  return $styles;
}
