<?php
/**
 * @file
 * Ads Theme module.
 */

global $ads_theme_css_list;

/**
 * Finds location of a CSS/LESS styles in the specified directory.
 *
 * @param string $module_name
 *   Name of the source module.
 * @param string $folder
 *   Path to the styles file, relative to the source module folder.
 * @param string $name
 *   Full name of the styles file.
 */
function ads_theme_find_styles($module_name, $folder, $name) {
  $cache    = &drupal_static(__FUNCTION__);
  $cache_id = 'theme_registry:ads_theme_find_styles_cache';

  if (!$cache) {
    $cache = cache_get($cache_id, 'cache');
    if ($cache && !empty($cache->data[$module_name][$folder][$name])) {
      return $cache->data[$module_name][$folder][$name];
    }

    if (!is_array($cache)) {
      $cache = array();
    }
  }

  $suggestions = array('less/', 'less/overrides/', 'less/overrides/' . $module_name . '/');

  global $theme;

  foreach ($suggestions as $suggestion) {
    $theme_path = drupal_get_path('theme', $theme) . '/' . $suggestion . $name;
    if (file_exists($theme_path)) {
      $cache[$module_name][$folder][$name] = $theme_path;
      cache_set($cache_id, $cache);
      return $theme_path;
    }
  }

  foreach ($suggestions as $suggestion) {
    $local_path  = $folder . '/' . $suggestion . $name;
    if (file_exists($local_path)) {
      $cache[$module_name][$folder][$name] = $local_path;
      cache_set($cache_id, $cache);
      return $local_path;
    }
  }

  foreach ($suggestions as $suggestion) {
    $module_path = drupal_get_path('module', $module_name) . '/' . $suggestion . $name;
    if (file_exists($module_path)) {
      $cache[$module_name][$folder][$name] = $module_path;
      cache_set($cache_id, $cache);
      return $module_path;
    }
  }
}

function ads_theme_init() {
  global $theme;

  ads_theme_add_css(drupal_get_path('theme', $theme) . '/less/page.less', array(
    'preprocess' => FALSE,
    'group' => CSS_THEME,
  ));
}

function ads_theme_add_css($path, $is_root = TRUE) {
  global $theme;

  $relative_path  = '';
  $root           = '';

  if ($is_root) {
    $root = drupal_get_path('theme', $theme);

    for ($i = count(explode('/', $path)); $i>1; $i--) {
      $relative_path .= "../";
    }
  }

  $relative_path .= $root . '/less/';

  drupal_add_css($path, array(
    'group' => CSS_THEME,
    'preprocess' => FALSE,
    'less' => array(
      'variables' => array(
        '@theme'      => '"' . $relative_path . 'page.less"',
        '@mixins'     => '"' . $relative_path . 'mixins.less"',
        '@layout'     => '"' . $relative_path . 'elements/layout.less"',
        '@typography' => '"' . $relative_path . 'elements/typography.less"',
      ),
    )
  ));
}